language: node_js

deploy:
  provider: s3
  access_key_id: AKIAIRO26MXZRB5AOADQ
  secret_access_key: JLnuekA9nRzN6pr1MdB0isGyrAC57Zmiz2r0ouO
  bucket: aaaxsource
  local-dir: "./dist"
  upload-dir: "/public"
  acl: public_read
  on:
    repo: adowning/aaax
